# Generated by Django 4.2.4 on 2024-08-26 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employeeexperience_employeeeducation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeeducation',
            old_name='coursepgra',
            new_name='coursegra',
        ),
        migrations.RenameField(
            model_name='employeeeducation',
            old_name='schoolclgpgra',
            new_name='schoolclggra',
        ),
        migrations.RemoveField(
            model_name='employeeeducation',
            name='percentagepgra',
        ),
        migrations.AddField(
            model_name='employeeeducation',
            name='percentagegra',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
